mine/urls.py
from django.urls import path
from . import views

app_name = 'mine'
urlpatterns = [
    path('', views.training_view, name='training')
]

mine_sys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('super_dash.urls')),
    path('mine/', include('mine.urls')),
]

super_dash/urls.py
from django.urls import path
from . import views

app_name = 'super_dash'
urlpatterns = [
    path('', views.index_view,
         name='index'),
    path('message/', views.message_view,
         name='message'),
    path('login/', views.login_view,
         name='login'),
    path('register/', views.register_view,
         name='register'),
    path('forgot-password/', views.forgot_password_view,
         name='forgot-password'),
    path('logout/', views.logout_view,
         name='logout'),
    path('profile/', views.profile_view,
         name='profile'),
    path('update_profile/', views.update_profile_view,
         name='update_profile'),
    path('get_task_status/', views.get_task_status_view,
         name='get_task_status'),
    path('upload_dataset/', views.upload_dataset_view,
         name='upload_dataset'),
    path('show_reports/', views.show_reports_view,
         name='show_reports'),
    path('get_dataset/', views.get_dataset_view,
         name='get_dataset'),
    path('settings/', views.settings_view,
         name='settings'),
    path('update_settings/', views.update_settings_view,
         name='update_settings'),
    path('get_dataset_overview/', views.get_dataset_overview,
         name='get_dataset_overview'),
    path('delete_dataset/', views.delete_dataset_view,
         name='delete_dataset'),
    path('echart/', views.echart_view,
         name='echart'),
    path('get_dataset_index/', views.get_dataset_index_view,
         name='get_dataset_index'),
    path('get_dataset_config/', views.get_dataset_config_view,
         name='get_dataset_config'),
    path('predict/', views.predict_view,
         name='predict')
]

handler404 = 'super_dash.views.response_not_found_handler'

super_dash/models.py
import json

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='recv_msg')
    sender = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='sended_msg')
    date = models.fields.DateField(auto_now=True)
    msg = models.fields.CharField(max_length=512)
    type = models.fields.CharField(max_length=16)


class Dataset(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='dataset')
    name = models.fields.CharField(max_length=255, unique=True)
    file = models.fields.FilePathField()
    algorithm = models.fields.CharField(max_length=255, null=True)
    config = models.fields.TextField(null=True, default={})
    result = models.fields.FilePathField(
        verbose_name="结果序列化文件")


class Photo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='photo')
    photo_url = models.fields.CharField(max_length=255, default='photo.jpg')

super_dash/forms.py
from django import forms

from super_dash.models import Dataset


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ['name', 'algorithm', 'config']

super_dash/views.py
# -*- coding: utf-8 -*-
import io
import os
import json
import pandas
import pickle
import logging
import requests
import jsonschema
import importlib

from json.decoder import JSONDecodeError
from django.shortcuts import render, redirect, reverse, HttpResponse, Http404
from django.http import StreamingHttpResponse
from django.db.utils import IntegrityError
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.contrib import auth

from . import utils
from . import settings
from . import echart_config
from .echart_config import data_map
from .models import Photo, Dataset, Message
from .signals import user_register
from .utils import get_user_info, get_dataset_status, get_training_result

from mine.signals import on_dataset_finish, on_exception_occur

LOG = logging.getLogger(__name__)


# user_register signal
def user_register_handler(**kwargs):
    admin_user = User.objects.get(username=settings.ADMIN_USER_NAME)
    init_msg = Message()
    init_msg.user = kwargs.get('user')
    init_msg.sender = admin_user
    init_msg.type = 'message'
    init_msg.msg = settings.MESSAGE
    init_msg.save()


user_register.connect(user_register_handler)


# dataset finish signal
def on_dataset_finish_handler(sender, **kwargs):
    models = kwargs.get('models')
    name = kwargs.get('name')
    predict = kwargs.get('predict')
    utils.cache_models(name, models)
    utils.cache("predict_%s" % name, pickle.dumps(predict))


on_dataset_finish.connect(on_dataset_finish_handler)


# exception signal
def on_exception_occur_handler(sender, **kwargs):
    name = kwargs.get('name')
    exception = kwargs.get('exception')
    LOG.warning("%s exception:<%s>" % (name, str(exception)))
    utils.cache_models(name, exception)


on_exception_occur.connect(on_exception_occur_handler)


def response_not_found_handler(request, exception):
    return render(request, '404.html', get_user_info(request.user), status=404)


@login_required(login_url=settings.LOGIN_URL)
def index_view(request):
    return render(request, 'index.html', get_user_info(request.user))


@login_required(login_url=settings.LOGIN_URL)
def message_view(request):
    return render(request, 'message.html', get_user_info(request.user))


def login_view(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request, username=username, password=password)
        if user:
            auth.login(request, user)
            return render(request, 'index.html', get_user_info(user))
        else:
            return render(request, 'login.html', {'error': True})
    return render(request, 'login.html')


def register_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        repassword = request.POST.get('repassword')
        if password == repassword and username and email:
            try:
                user = User.objects.create_user(username, email, password)
            except IntegrityError:
                return render(request, 'register.html', {'error': True})
            user.first_name = firstname if firstname else None
            user.last_name = lastname if lastname else None

            photo = Photo()
            photo.user = user
            photo.photo_url = 'photo.jpg'
            photo.save()

            user.save()
            user_register.send(user.__class__, request=request, user=user)
            user_info = get_user_info(user)
            auth.login(request, user)
            return render(request, 'index.html', user_info)
        else:
            return render(request, 'register.html', {'error': True})

    return render(request, 'register.html')


def forgot_password_view(request):
    return render(request, 'forgot-password.html')


@login_required(login_url=settings.LOGIN_URL)
def logout_view(request):
    auth.logout(request)
    return render(request, 'login.html')


@login_required(login_url=settings.LOGIN_URL)
def profile_view(request):
    return render(request, 'profile.html', get_user_info(request.user))


@login_required(login_url=settings.LOGIN_URL)
def update_profile_view(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    photo_file = request.FILES.get('photo')
    user = request.user
    if username:
        user.username = username
        if password:
            user.set_password(password)
        if photo_file:
            photo_path = os.path.join(settings.BASE_UPLOAD_PHOTO_DIR,
                                      photo_file.name)
            photo = user.photo
            photo.photo_url = photo_file.name
            with open(photo_path, 'wb+') as fp:
                for chunk in photo_file.chunks():
                    fp.write(chunk)
            photo.save()
        user.save()
    else:
        user_info = get_user_info(user)
        user_info.setdefault('error', True)
        return render(request, 'profile.html', user_info)

    return render(request, 'profile.html', get_user_info(user))


@login_required(login_url=settings.LOGIN_URL)
def get_task_status_view(request):
    name = request.GET.get('name')
    return HttpResponse(json.dumps({
        "status": get_dataset_status(name)
    }))


@login_required(login_url=settings.LOGIN_URL)
def upload_dataset_view(request):
    dataset_file = request.FILES.get('dataset')
    name = request.POST.get('name')
    if not dataset_file and not name:
        return render(request, 'index.html', get_user_info(request.user))
    dataset_model = Dataset()
    dataset_model.user = request.user
    dataset_model.file = dataset_file.name
    dataset_model.name = name
    try:
        dataset_model.validate_unique()
    except ValidationError:
        return render(request, 'index.html', get_user_info(request.user))

    upload_to = os.path.join(settings.BASE_UPLOAD_DATASET_DIR,
                             dataset_file.name)
    with open(upload_to, 'wb+') as fp:
        for chunk in dataset_file.chunks():
            fp.write(chunk)

    dataset_model.save()
    # return render(request, 'index.html', get_user_info(request.user))
    return redirect("super_dash:settings")


@login_required(login_url=settings.LOGIN_URL)
def show_reports_view(request):
    user_info = get_user_info(request.user)
    return render(request, 'reports.html', user_info)


@login_required(login_url=settings.LOGIN_URL)
def get_dataset_index_view(request):
    name = request.GET.get('dataset')
    try:
        dataset = Dataset.objects.get(user=request.user, name=name)
    except Dataset.DoesNotExist:
        return HttpResponse(json.dumps({"index": []}))
    file_name = dataset.file
    file_path = os.path.join(settings.BASE_UPLOAD_DATASET_DIR, file_name)
    index = pandas.read_csv(file_path).columns
    return HttpResponse(json.dumps({"index": list(index)}))


@login_required(login_url=settings.LOGIN_URL)
def get_dataset_view(request):
    name = request.GET.get('dataset')
    echart_type = request.GET.get('echart_type')
    index = request.GET.get('index')

    try:
        Dataset.objects.get(user=request.user, name=name)
    except Dataset.DoesNotExist:
        raise Http404()

    res = get_training_result(name)
    if 'exp_stk' in res:
        return HttpResponse(json.dumps({
            "error": True,
            "exception": str(res.get('exp'))
        }))

    try:
        res = res.get(getattr(data_map, echart_type.upper()), [])
    except AttributeError:
        raise Http404()

    if echart_type.upper() not in ["TREE", "SCATTER"]:
        for item in res:
            if index == item.get('name'):
                res = item.get('data')

    return HttpResponse(json.dumps(res))


@login_required(login_url=settings.LOGIN_URL)
def get_dataset_overview(request):
    dataset_name = request.GET.get('dataset')
    try:
        dataset = Dataset.objects.get(user=request.user, name=dataset_name)
    except Dataset.DoesNotExist:
        raise Http404()
    if dataset:
        ds_file_path = os.path.join(settings.BASE_UPLOAD_DATASET_DIR, dataset.file)
        df = pandas.read_csv(ds_file_path).head()
        return render(request, 'dataset_overview.html', {
            "column_index": df.columns,
            "table": (row[1] for row in df.iterrows())
        })


@login_required(login_url=settings.LOGIN_URL)
def settings_view(request):
    return render(request, 'settings.html', get_user_info(request.user))


@login_required(login_url=settings.LOGIN_URL)
def update_settings_view(request):
    name = request.POST.get('name')
    algorithm = request.POST.get('algorithm')
    raw_config = request.POST.get('config')

    user_info = get_user_info(request.user)

    try:
        config = json.loads(raw_config)
        importlib.import_module(algorithm)
        schema = utils.get_schema(algorithm)
        if schema:
            jsonschema.validate(config, schema)
    except JSONDecodeError as e:
        # for dataset in user_info.get('datasets'):
        #     if dataset['name'] == name:
        #         dataset['algorithm'] = algorithm
        #         dataset['config'] = config
        user_info.setdefault('error', '配置信息错误')
        return render(request, 'settings.html', user_info)
    except jsonschema.exceptions.ValidationError as e:
        user_info.setdefault('error', e.message)
        return render(request, 'settings.html', user_info)
    except ImportError as e:
        user_info.setdefault('error', '无法找到算法插件')
        return render(request, 'settings.html', user_info)
    dataset = Dataset.objects.get(name=name, user=request.user)

super_dash/templates/frame.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}大数据分析平台{% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template-->
  <link href="/static/css/super_dash.min.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'super_dash:index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{% block logo_title %}大数据分析平台{% endblock %}</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'super_dash:index' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>menu</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">menu:</h6>
            <a class="collapse-item" href="{% url 'super_dash:show_reports' %}">show reports</a>
            <a class="collapse-item" href="{% url 'super_dash:settings' %}">Settings</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">
                  {% if alter_nu > 9 %}
                    9+
                  {% else %}
                    {{ alter_nu }}
                  {% endif %}
                </span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                {% for date, msg in alters %}
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                      <div class="icon-circle bg-primary">
                        <i class="fas fa-file-alt text-white"></i>
                      </div>
                    </div>
                    <div>
                      <div class="small text-gray-500">{{ date }}</div>
                      <span class="font-weight-bold">{{ msg }}</span>
                    </div>
                  </a>
                {% endfor %}
                <a class="dropdown-item text-center small text-gray-500" href="{% url 'super_dash:message' %}">Show All Alerts</a>
              </div>
            </li>

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">
                  {% if message_nu > 9 %}
                    9+
                  {% else %}
                    {{ message_nu }}
                  {% endif %}
                </span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                {% for date, msg, snd_photo in messages %}
                  <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                      <img class="rounded-circle" src="{{ snd_photo }}" alt="">
                      <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                      <div class="text-truncate">{{ msg }}</div>
                      <div class="small text-gray-500">{{ date }}</div>
                    </div>
                  </a>
                {% endfor %}
                <a class="dropdown-item text-center small text-gray-500" href="{% url 'super_dash:message' %}">Read More Messages</a>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ username }}</span>
                <img class="img-profile rounded-circle" src="{{ photo_url }}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'super_dash:profile' %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
        {% block frame_body %}{% endblock %}
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; syk 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'super_dash:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/js/super_dash.min.js"></script>
  {% block script %}{% endblock %}
</body>

</html>

super_dash/templates/profile.html
{% extends 'frame.html' %}

{% block frame_body %}
  <div class="row">
    <div class="col-lg-6">
      <div class="p-5">
        <div class="text-center">
          <h1 class="h4 text-gray-900 mb-4">Profile</h1>
        </div>

        <form class="user" method="post" action="{% url 'super_dash:update_profile' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <img class="col-12 p-5" src="{{ photo_url }}">
          <div class="form-group">
            <input type="file" id="inputFile" name="photo">
            <p>上传头像</p>
          </div>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" id="inputUsername" value="{{ username }}" name="username">
          </div>
          <div class="form-group">
            <input readonly type="email" class="form-control form-control-user" id="inputEmail" aria-describedby="emailHelp" value="{{ email }}" name="email">
          </div>
          <div class="form-group">
            <input type="password" class="form-control form-control-user" id="inputPassword" placeholder="******" name="password">
          </div>
          <input class="btn btn-primary btn-user btn-block" type="submit" value="Submit">
        </form>
        {% if error %}
          <p class="text-center" style="color: red;">update profile fail!</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

super_dash/templates/reports.html
{% extends 'frame.html' %}

{% block frame_body %}
  <h3 style="display:none" id="error">配置信息可能有误，导致数据分析失败！</h3>
  <div class="row">
    <div class="col-3">
      <a class="dropdown-toggle" href="#" id="datasetDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="text-decoration: none;">
        <span class="mr-2 d-none d-lg-inline text-gray-600">选择数据集</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="datasetDropdown">
        {% for dataset in datasets %}
          <a class="dropdown-item p-2" href="#" onclick="showChart(event)">{{ dataset.name }}</a>
          <div class="dropdown-divider"></div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div id="dataset_report" style="display:none;">
    <div id="dataset_overview"></div>

    <div class="row">
      <div class="col-6 p-1">
        <div class="row" id="gridDropdown">
          <div class="col-3">
            <a class="dropdown-toggle" href="#" id="gridDropdownItems" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="text-decoration: none;">
              <span class="mr-2 d-none d-lg-inline text-gray-600">index</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="gridDropDownItems" id="index"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-6">
        <iframe id="frame-1" style="display:none;"></iframe>
      </div>

      <div class="col-6">
        <iframe id="frame-2" style="display:none;"></iframe>
      </div>
    </div>

    <div class="row">
      <div class="col-6">
        <iframe id="frame-3"  style="display:none;"></iframe>
      </div>

      <div class="col-6">
        <iframe id="frame-4"  style="display:none;"></iframe>
      </div>
    </div>
  </div>

  <div class="row p-3" style="display:none" id="upload_predict_file">
    <div class="col-3" style="margin:auto">
      <form method="post" action="{% url "super_dash:predict" %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" id="predict_dataset" style="display:none" name="dataset_name"/>
        <input type="file" name="dataset"/>
        <input type="submit" class="btn btn-primary btn-block" value="上传"/>
      </form>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script lang="javascript" src="/static/js/echarts/echarts.min.js"></script>
  <script lang="javascript" src="/static/js/echarts/echarts-gl.min.js"></script>
  <script lang="javascript" src="/static/js/echarts/vintage.js"></script>
  <script lang="javascript">
    let echart_base_url = "{% url 'super_dash:echart' %}";
    let echart_type = [];
    let dataset = null;

    function showChart(event) {
      document.getElementById("dataset_report").style = 'display: block;';
      dataset = event.target.innerText;

      document.getElementById("upload_predict_file").setAttribute("style", "display:block");
      document.getElementById("predict_dataset").setAttribute("value", dataset);

      let dataset_overview = document.getElementById("dataset_overview");
      $.get('{% url "super_dash:get_dataset_overview" %}', {dataset: dataset}, function(data){
        dataset_overview.innerHTML = data;
      });

      $.get('{% url "super_dash:get_dataset_index" %}', {dataset: dataset}, function(data){
        let index_ele = document.getElementById("index");
        index_ele.innerText = "";
        for(let i of JSON.parse(data).index){
          let a = document.createElement('a');
          a.setAttribute('class', 'dropdown-item p-2');
          a.setAttribute('onclick', 'onChangeIndex(event)');
          a.innerText = i;
          index_ele.append(a);
          let div_ele = document.createElement('a');
          div_ele.setAttribute('class', 'dropdown-divider');
          index_ele.append(div_ele);
        }
      });

      $.get('{% url "super_dash:get_dataset_config" %}', {dataset: dataset}, function(data){
        let config = JSON.parse(data);
        if(config.chart){
          echart_type = config.chart.splice(0, 4);
        }

        let frames = document.getElementsByTagName('iframe');
        for(let f of frames){
          f.setAttribute("style", "display:none");
        }

        for(let i=0; i<echart_type.length; i++){
          let frame = document.getElementById('frame-'+(i+1));
          frame.setAttribute('src', echart_base_url+'?dataset='+dataset+'&echart_type='+echart_type[i]);
          frame.setAttribute('style', 'width:100%;height:500px;display: block');
        }
      });
    }

    function onChangeIndex(event){
      let index = event.target.innerText;
      for(let i=0; i<echart_type.length; i++){
        let frame = document.getElementById('frame-'+(i+1));
        frame.setAttribute('src', echart_base_url+'?dataset='+dataset+'&echart_type='+echart_type[i]+'&index='+index);
      }
    }
  </script>
{% endblock %}